title: Web Developer
author: Ganesh Telagamsetti
email: ganeshtelagamsetti81@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The role is responsible for designing, coding and modifying websites, from layout to function and according to a client's specifications. Strive to create visually appealing sites that feature user-friendly design and clear navigation.

# social links
twitter_username: GTelagamsetti # DO NOT include the @ character, or else the build will fail!
github_username:  ganeshtelagamsetti # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
